# CONFIG: Replace this with your own application name
application: danfortheast
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed\.png
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /vendor
  static_dir: static/vendor

# Stuff like cron jobs and email taskqueues
- url: /tasks/.*
  script: tasks.app
  login: admin

# The self-serve member join form and PayPal processing
- url: /self-serve/process-member-worker
  script: self-serve.app
  login: admin
- url: /self-serve/expire-member-candidates
  script: self-serve.app
  login: admin
- url: /self-serve/.*
  script: self-serve.app

# Everything else -- direct member join and renewal, maps stuff
- url: /.*
  script: main.app


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^static/vendor/bootstrap/bootstrap-source.*$
